import { Solicitud } from "./types";

function isoDaysFromToday(days: number): string {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const solicitudesMock: Solicitud[] = [
  {
    id: "1",
    solicitante: "Juan Pérez",
    motivo: "Solicita reunión por obra de pavimentación en Barrio Norte",
    fecha: isoDaysFromToday(0),
    hora: "09:30",
    estado: "agendada",
    contacto: "juan.perez@mail.com",
    institucion: "Vecinos Barrio Norte",
    observaciones: "Vendrá acompañado por dos vecinos más.",
    creadaEn: isoDaysFromToday(-5),
  },
  {
    id: "2",
    solicitante: "María González",
    motivo: "Presentación de proyecto cultural para escuelas",
    fecha: isoDaysFromToday(0),
    hora: "11:00",
    estado: "agendada",
    contacto: "3415-123456",
    institucion: "Centro Cultural Municipal",
    creadaEn: isoDaysFromToday(-3),
  },
  {
    id: "3",
    solicitante: "Cooperativa El Progreso",
    motivo: "Pedido de subsidio para maquinaria",
    fecha: isoDaysFromToday(2),
    hora: "10:00",
    estado: "agendada",
    contacto: "cooperativa@elprogreso.org",
    institucion: "Cooperativa El Progreso",
    creadaEn: isoDaysFromToday(-7),
  },
  {
    id: "4",
    solicitante: "Roberto Sánchez",
    motivo: "Reclamo por luminaria pública en calle San Martín",
    fecha: isoDaysFromToday(3),
    estado: "pendiente",
    contacto: "3415-987654",
    creadaEn: isoDaysFromToday(-1),
  },
  {
    id: "5",
    solicitante: "Club Deportivo Unión",
    motivo: "Solicita uso del polideportivo municipal",
    fecha: isoDaysFromToday(5),
    hora: "16:00",
    estado: "agendada",
    institucion: "Club Deportivo Unión",
    contacto: "info@clubunion.com.ar",
    creadaEn: isoDaysFromToday(-2),
  },
  {
    id: "6",
    solicitante: "Asociación de Comerciantes",
    motivo: "Propuesta de feria navideña en plaza central",
    fecha: isoDaysFromToday(7),
    estado: "pendiente",
    institucion: "Asoc. Comerciantes del Centro",
    contacto: "comercio@centro.org.ar",
    observaciones: "Necesitan respuesta antes de fin de mes.",
    creadaEn: isoDaysFromToday(-1),
  },
  {
    id: "7",
    solicitante: "Laura Méndez",
    motivo: "Consulta sobre habilitación comercial",
    fecha: isoDaysFromToday(-2),
    hora: "09:00",
    estado: "realizada",
    contacto: "laura.mendez@mail.com",
    creadaEn: isoDaysFromToday(-10),
  },
  {
    id: "8",
    solicitante: "Carlos Ríos",
    motivo: "Pedido de audiencia personal",
    fecha: isoDaysFromToday(-4),
    estado: "no_realizada",
    contacto: "3415-555000",
    observaciones: "Derivado a la Secretaría de Gobierno.",
    motivoNoRealizada: "El solicitante no se presentó. Se derivó a la Secretaría de Gobierno.",
    creadaEn: isoDaysFromToday(-12),
  },
  {
    id: "9",
    solicitante: "Escuela N°34",
    motivo: "Invitación a acto del 25 de mayo",
    fecha: isoDaysFromToday(4),
    hora: "10:30",
    estado: "agendada",
    institucion: "Escuela Primaria N°34",
    contacto: "escuela34@edu.gob.ar",
    creadaEn: isoDaysFromToday(-6),
  },
  {
    id: "10",
    solicitante: "Vecinos Calle Belgrano",
    motivo: "Problema con desagües pluviales",
    fecha: isoDaysFromToday(1),
    hora: "15:00",
    estado: "agendada",
    institucion: "Comisión vecinal",
    creadaEn: isoDaysFromToday(-4),
  },
  {
    id: "11",
    solicitante: "Sindicato Municipal",
    motivo: "Reunión paritaria",
    fecha: isoDaysFromToday(6),
    hora: "11:00",
    estado: "pendiente",
    institucion: "SOEM",
    creadaEn: isoDaysFromToday(-1),
  },
];
